<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <None Remove="SqlStatementsForSetup\SetupSlowMemoryOptimized.sql" />
      <Content Include="SqlStatementsForSetup\SetupSlowMemoryOptimized.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />
    </ItemGroup>

</Project>
